[package]
name = "gw2-pf-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
gw2-pf-rs-derive = { path = "../gw2-pf-derive" }

[dev-dependencies]
rust-crypto = "^0.2"

[features]
debug-parsing = []
